{{- range $envName, $envData := .Values.environments }}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-{{ $envName }}
spec:
  acme:
    server: {{ $envData.server }}
    email: {{ $envData.email }}
    privateKeySecretRef:
      name: letsencrypt-{{ $envName }}
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx
{{- end }}